Repository integr8ly/application-monitoring-operator, pull requests merged in 2020-07, with the labels that each got.

#141 Fix to remove the readiness probe in the operator yaml.
  templates/grafana-operator.yaml
Labels: approved

#142 Fix Markdown link format in README
  README.md
Labels: approved, lgtm, needs-ok-to-test

#143 Update OWNERS
  OWNERS
Labels: approved, lgtm
